version: "3.9"

services:
  db:
    image: postgres
    container_name: myproject-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - "5432:5432"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: myproject-backend
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_NAME: myprojectdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: myproject-frontend
    environment: 
      - CHOKIDAR_USEPOLLING=true
    #command: npm run serve
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend
  redis:
    image: redis:alpine
    container_name: myproject-redis
    depends_on: 
      - backend


